### ISSUE TITLE
Links to more applications using esri-system-js

### ISSUE THREAD

**Issue by tomwayson** [Esri/esri-system-js#14]
If you've got a publicly facing application built w/ esri-system-js, we want to hear about it. Leave a comment on this issue w/ the application name and URL and we'll add it to the [Example Applications section of the README](https://github.com/Esri/esri-system-js#example-applications), or better yet, make a PR with your own updates to the README.

Thank you!

**Comment by jwerts** [comment]
@tomwayson This is an example app/blog post I did using esri-system-js if you're interested in including:

http://joshwerts.com/jsapi4-angular2/
http://joshwerts.com/blog/2016/05/17/esri-javascript-api-4-with-angular-2-and-typescript/

**Comment by tomwayson** [comment]
Thanks @jwerts, I've [added this to the README](https://github.com/Esri/esri-system-js/#example-applications). I like that you include the set up for Jasmine/Karma! 

I'd love to see how that works w/ v1.0.0-beta.0. I've opened a [PR](https://github.com/jwasilgeo/angular2-esri-playground/pull/10) to @jwasilgeo's repo which could give you an idea of the changes that are involved. The major benefit is being able to use the type definitions from Esri.

**Comment by jwerts** [comment]
@tomwayson Cool!  I was waiting to see that PR before updating to v1.0.0-beta.0.  Should be testing that out soon.  Thanks for your all your work on this!

**Comment by jwerts** [comment]
Updated my stuff to use v1.0.0-beta.0.  Everything's working great now - did have one stumbling block though.  Took a while to realize that the module property in **tsconfig.json** needed to be "system".  After setting that, tsc was compiling properly and VS Code was happy w/ intellisense working.

```js
{
  "compilerOptions": {
    "target": "es5",
    "module": "system",
...
```

**Comment by tomwayson** [comment]
Awesome! Looks like you even updated the code snippets in the blog post.

Good point about the `compilerOptions.module` property. TBH, I didn't even realize that was a requirement. I tried setting that to `"amd"` and saw the TS compile errors like `[ts Module '"esri/views/MapView"' has no default export.` in VS Code, but the app did still seem to compile and work in the browser.

Thanks for bringing that to my attention, I'll make a note of that in the README.

**Comment by S-Gaballah** [comment]
@tomwayson I added startup app using esri-system-js to include if you like it

https://github.com/S-Gaballah/Angular-Esri-ArcGIS-API-3

I appreciate all comments

**Comment by tomwayson** [comment]
thanks @S-Gaballah!

As I'm not doing Angular development these days I'm not really in a position to comment on your project, but I added the link to [the README](https://github.com/Esri/esri-system-js/#example-applications).
