### ISSUE TITLE
Note that tsconfig.json module needs to be "system" to prevent TS compile errors

### ISSUE THREAD

**Issue by tomwayson** [Esri/esri-system-js#18]
Add a note to the README.

See https://github.com/Esri/esri-system-js/issues/14#issuecomment-231249115

**Comment by nickcam** [comment]
Hi @tomwayson,

The time has come that I needed to produce a prod build for angular 2/esri 4. 
Rollup looks great so want to use that, and also ahead of time compilation (ngc). Both of which don't play nice with esri-system-js in it's current form.

Had to get other module types besides 'system' to work.
Managed to update esriSystem.ts to allow module types of commonjs and es2015...which is enough for my builds to get going...think amd works as well.

It does require changing the import statements to be like this though -
```
import * as Map from 'esri/Map'; 
```
To be honest I don't think I'm going to use it anyway though, seems like too many workarounds/hacks when I can just edit the official typings file exports statements instead.
...but if yourself or anyone else is interested I can raise a PR?

**Comment by nickcam** [comment]
Scrap that last comment, just found this little gem while searching for something else.
Adding this to tsconfig.json compilerOptions allows the official typings to compile using any module type on the current code. Apparently using 'system' as the module sets this to true by default which is why it has been working.

```
"allowSyntheticDefaultImports": true
```

**Comment by tomwayson** [comment]
Interesting. I'd gladly welcome a PR.

**Comment by nickcam** [comment]
Sorry got ahead of myself with the code change...as I said you just need to set this compiler flag in tsconfig and it will compile across different module systems - `"allowSyntheticDefaultImports": true`

So no need for a PR, except maybe an update to the readme to highlight that flag.
