### ISSUE TITLE
Is js api 3.x supported?

### ISSUE THREAD

**Issue by dcworldwide** [Esri/esri-system-js#19]
Is js api 3.x supported? Thanks

**Comment by tomwayson** [comment]
Yes.

This plunkr shows an example: http://plnkr.co/edit/bZNzdI?p=preview

Also the angular2-esri-example (3.x) repo used to use esri-system-js [before switching over to webpack](https://github.com/tomwayson/angular2-esri-example/pull/13/files).

**Comment by dcworldwide** [comment]
Thanks.

Do you have a webpack + react example?

**Comment by tomwayson** [comment]
No, but apparently [you do](https://github.com/dcworldwide/esri-webpack).

Sorry I missed this comment, but it looks like you found https://github.com/lobsteropteryx/esri-webpack-typescript anyway.
