### ISSUE TITLE
Convert to a systemjs plugin?

### ISSUE THREAD

**Issue by roemhildtg** [Esri/esri-system-js#20]
Would it be possible to convert this to a [SystemJS Plugin](https://github.com/systemjs/systemjs/blob/master/docs/creating-plugins.md)? That way you could do something like this in your code, and you wouldn't have to pre-register any modules. 

```
import {Map} from 'esri/Map!esri';
```

**Comment by tomwayson** [comment]
I looked at that briefly back before creating this repo, and if I recall, asked @odoe if he had tried it yet, and I think he said he couldn't get it to work.

**Comment by tomwayson** [comment]
FYI - I talked to @odoe after you opened this issue a few weeks back, and there was a glimmer in his eye that indicated that there might be something else to try.

If we could get that to work, I'd say it's a better solution than what we're doing here.

**Comment by roemhildtg** [comment]
That is excellent. I started looking into it, https://gist.github.com/roemhildtg/4dce79f9bffe74b99a6a6cea3f44604f but it gives an error about a plugin having system.register in it. I can't exactly recall the error message though.

**Comment by odoe** [comment]
I'll try to revisit this. I'll be spending the next couple of weeks working with Angular 2/SystemJS, so I'll try to work this in as well.

**Comment by tomwayson** [comment]
Cool. If that works, I assume that would be it's own repo, so I'm going to press ahead w/ a [v1]( https://github.com/Esri/esri-system-js/milestone/1) for this lib as that is long overdue.

**Comment by diegohb** [comment]
Coming out the dev conference... any update/progress on this effort?  I read someone summarize the problem on twitter as it being about not being able to supply defaultJsExtension prop ANd another property on the systemjs config..

**Comment by tomwayson** [comment]
I'm not using Angular these days, and even if I was, I'd be using webpack to bundle my modules. I know that even in webpack apps, SystemJS can be used to lazy load bundles at runtime, but for lazy loading the ArcGIS API and modules, I'd use [esri-loader](https://github.com/tomwayson/esri-loader). So I'm not actively working on this these days.

What is your use case? Are you using JSPM?

**Comment by roemhildtg** [comment]
@tomwayson I'm using npm and [stealjs](http://stealjs.com/), which is based on SystemJS but lets you load from node_modules. 

Steal also transpiles es6 modules on the fly, so ultimately I'd like to do something like this:

```javascript
import Map from 'esri/map'; 

// or 
import Map from 'esri/map!esriPlugin';
```

**Comment by beginor** [comment]
Finally, I have made a [systemjs.loader.dojo.js](https://gist.github.com/beginor/7dbe633ef26e98fe0ba70bcb1d191b8c) plugin works with Angular v2.4.7 and ArcGIS API for Javascript v4.2, and there is a demo: [ng2-esri-demo](https://github.com/beginor/ng2-esri-demo)

**Comment by tomwayson** [comment]
Nice work @beginor!

I tried @beginor's demo app, and it seems to work other than this AoT build issue: https://github.com/beginor/ng2-esri-demo/issues/2

@diegohb and @roemhildtg I suggested you both give [his gist](https://gist.github.com/beginor/7dbe633ef26e98fe0ba70bcb1d191b8c) (which I believe is based on @roemhildtg's gist above)  a try in your own applications. 

If the pattern works for you guys, then maybe you guys could work together to [create a repository for and publish the plugin](https://gist.github.com/beginor/7dbe633ef26e98fe0ba70bcb1d191b8c#gistcomment-2003945).

**Comment by beginor** [comment]
@tomwayson No, the demo can not build with aot (rollup), it is just a SystemJS loader plugin. Any one who knows how to build dojo with rollup?

**Comment by tomwayson** [comment]
I know how to *not* build dojo w/ rollup, which is probably the best strategy, and have [an example repo](https://github.com/tomwayson/esri-rollup-example). I don't think rollup is your problem (yet). See my comment: https://github.com/beginor/ng2-esri-demo/issues/2#issuecomment-280863333

Regardless of whether or not you choose to try and get the AoT build working, I think it's worthwhile to create a repo for the SystemJS plugin and publish it to make it easier for others to use.

**Comment by beginor** [comment]
npm package: https://www.npmjs.com/package/systemjs-plugin-dojo 
github repo: https://github.com/beginor/systemjs-plugin-dojo
demo repo: https://github.com/beginor/ng2-esri-demo

**Comment by tomwayson** [comment]
Awesome work @beginor!

**Comment by diegohb** [comment]
@tomwayson thanks! I am trying to use JSPM and [Aurelia](aurelia.io) for MVVM framework. Currently I'm trying to focus on just SystemJS config w/ Dojo.. I will try out the SystemJS loader plugin by @beginor and I'll share my results and publish a demo repo if I'm successful.  thanks!
