### ISSUE TITLE
Angular 2 RTM

### ISSUE THREAD

**Issue by PivotalAnimal** [Esri/esri-system-js#21]
I was curious if you plan to upgrade this project to Angular 2 RTM?

**Comment by jwasilgeo** [comment]
@PivotalAnimal this will work as it currently is with the Angular 2 release.  Some of the [example apps listed in the readme](https://github.com/Esri/esri-system-js#example-applications) are using the latest version of Angular 2 and demonstrate how to use this library with it.  Perhaps I misunderstood your question?

**Comment by PivotalAnimal** [comment]
You're right. I think I was confused. ;-)
