### ISSUE TITLE
trouble using the Esri JS API locally

### ISSUE THREAD

**Issue by solowt** [Esri/esri-system-js#23]
I've had no issues pulling from the CDN as in the examples, but when I try to use esri-system-js when loading the jsapi modules locally, I get this error: 

`system.src.js:3056 Uncaught TypeError: Invalid System.register call. Anonymous System.register calls can only be made by modules loaded by SystemJS.import and not via script tags.`

I'm just loading a dojoConfig and then dojo.js before I pass the packages I want to esriSystem:

index.html:

```
<script src="src/app/dojoConfig.js"></script>
<script src="src/app/jsapi/dojo/dojo.js"></script>
<script src="src/app/load.js"></script>
```

dojoConfig.js:

```js
window.dojoConfig = {
    async: true,
    baseUrl: "app",
    debug: false,
    parseOnLoad: false,
    packages: [
      {"name": "dojo", "location": "src/app/jsapi/dojo"},
      {"name": "dijit", "location": "src/app/jsapi/dijit"},
      {"name": "dojox", "location": "src/app/jsapi/dojox"},
      {"name": "esri", "location": "src/app/jsapi/esri"},
    ]
};
```

app.load.ts:

```ts
declare var System: any;
declare var esriSystem: any;

esriSystem.register([
    "esri/Map",
    "esri/views/MapView"
], function(){
    System.import('app').catch(function(err){ console.error(err); });
});
```

Any suggestions?  The error occurs during the dojo.require step but I'm unsure how this pattern differs from loading from a CDN.

**Comment by tomwayson** [comment]
Is `<script src="src/app/jsapi/dojo/dojo.js"></script>` the output of a Dojo build of the ArcGIS API for JavaScript? If it is an unbuilt source file, then I don't expect it will work.

What method did you use to get the JSAPI locally? Download the SDK, or bower install?

**Comment by solowt** [comment]
I had forgotten to build it, everything working as expected now.

Thanks!
