### ISSUE TITLE
Local repository

### ISSUE THREAD

**Issue by Basicside** [Esri/esri-system-js#28]
Is it possible to load the esri modules from a local folder ?

**Comment by Basicside** [comment]
it's seems that there is no big secret to this, I found this article http://support.esri.com/technical-article/000011974, following this and changing the [HOSTNAME_AND_PATH_TO_JSAPI] to my url, with the basic esriSystem configuration, everything seems to look fine

**Comment by roemhildtg** [comment]
You can download this too: https://github.com/Esri/arcgis-js-api
