### ISSUE TITLE
How to register a plugin?

### ISSUE THREAD

**Issue by coreyog** [Esri/esri-system-js#9]
I want to require a third party plugin: http://www.arcgis.com/home/item.html?id=a8f78cc6adea48cb8e962d7e36b9d010

Their examples use old non-Angular, non-esriSystem ways to import the custom layer by using djConfig.

How can esriSystem let me configure for the import of this layer?

**Comment by jwasilgeo** [comment]
@coreyog I am working on a plnkr to try to illustrate how this can be done.  I'll update this thread when I have a working example.

**Comment by jwasilgeo** [comment]
Check out this plnkr using the "Esr/cluster-layer-js" repo on a map:
http://plnkr.co/edit/bZNzdI?p=preview


The way that I've put this together, @coreyog, is that one can register plugins / packages to inform Dojo how to load external resources (see index.html `dojoConfig`).  Then, in esri-system-js, you can register these packages just like any other module in the Esri JSAPI (see app/esriLoad.js).

**Comment by jwasilgeo** [comment]
Does anyone else have other possible solutions in mind or feedback on the above?

**Comment by tomwayson** [comment]
Nice work @jwasilgeo. That's exactly how I would have done it.

**Comment by coreyog** [comment]
It seems to be working. Now I'm getting an error about `dojo.provide` not existing but that may be the plugin to blame.

**Comment by tomwayson** [comment]
Thanks @coreyog. Based on your comment, I'm closing this issue for now. Feel free to re-open if needed.
